月の勤務情報(contract/{contractId}/{yearMonth})の実装
kensuke-sakagami/-end-project pull request #24
Opened 2022-08-05 11:35 UTC by kensuke-sakagami

2022-08-06 02:44 UTC, kensuke-sakagami commented
修正点
・delete,changeを実行した後の画面遷移先を(contract/{monthId}/{yearMonth})に変更
・時間のinput Formのtypeを変更
・workTimeMinuteの処理に不備があったため変更

2022-08-06 03:11 UTC, ShizukaKurosawa requested changes

2022-08-06 03:11 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/ApplicableMonthListController.java
> +		int	endMin = changeForm.getEndTime().getMinute() + changeForm.getEndTime().getHour() * 60;
`int endMin`のスペースが全角になっているので修正すること

2022-08-06 03:11 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/model/ContractChangeForm.java
> +}
下記修正チケットの￥修正対象に`ContractChangeForm`クラスも追加する
https://www.notion.so/Form-d9470a54aa134a398c832eeae88ffda1

2022-08-06 03:11 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/model/ContractDeleatForm.java
> +}
下記チケットの修正対象に`ContractDeleatForm`クラスも追加する
https://www.notion.so/Form-d9470a54aa134a398c832eeae88ffda1

2022-08-07 02:03 UTC, ShizukaKurosawa approved these changes

2022-08-07 02:04 UTC, merged